#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : multimon-ng
Version  : 1.1.9
Release  : 11
URL      : https://github.com/EliasOenal/multimon-ng/archive/1.1.9/multimon-ng-1.1.9.tar.gz
Source0  : https://github.com/EliasOenal/multimon-ng/archive/1.1.9/multimon-ng-1.1.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: multimon-ng-bin = %{version}-%{release}
Requires: multimon-ng-license = %{version}-%{release}
Requires: multimon-ng-man = %{version}-%{release}
Requires: sox
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(x11)
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : sox

%description
multimon-ng is the successor of multimon. It decodes the following digital transmission modes:

%package bin
Summary: bin components for the multimon-ng package.
Group: Binaries
Requires: multimon-ng-license = %{version}-%{release}

%description bin
bin components for the multimon-ng package.


%package license
Summary: license components for the multimon-ng package.
Group: Default

%description license
license components for the multimon-ng package.


%package man
Summary: man components for the multimon-ng package.
Group: Default

%description man
man components for the multimon-ng package.


%prep
%setup -q -n multimon-ng-1.1.9
cd %{_builddir}/multimon-ng-1.1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614713873
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1614713873
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/multimon-ng
cp %{_builddir}/multimon-ng-1.1.9/COPYING %{buildroot}/usr/share/package-licenses/multimon-ng/4cc77b90af91e615a64ae04893fdffa7939db84c
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/multimon-ng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/multimon-ng/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/multimon-ng.1
